[project]
name = "handwritten-equation-solver"
version = "1.0.0"
description = "AI-powered handwritten mathematical equation solver"
requires-python = ">=3.10,<3.12"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

